config:
    connection:
        Google API key: AIzaSyAuCGEUKMCeW5P9sTk96a9hsunAtmnwGNo
        Discord bot token: # Discord bot token
    main:
        Ping Every x Minutes: 5 # 5-15 minutes should be ok, anything lower not recommended, because the API traffic will be used up very quickly otherwise.
    Discord Channel:
        0:
            channelID: 669235898168246283 # Discord channel ID
            New video: ":film_frames: **{0} HAS UPLOADED A NEW VIDEO!** :film_frames:" # Message that appears when a YouTuber has uploaded a new video
            Livestream: ":red_circle: **{0} IS LIVESTREAMING NOW!** :red_circle:" # Message that appears when a YouTuber is livestreaming
            # My server content-sharing
      
    YouTubers:
        0:
            name: SHIN OP HAI # Name that will be displayed in discord, mentions can be used with <@DiscordUserID>
            channelID: UCZz0bZsOk-h_jzUAVrgndog  # YouTube Channel ID
            # Some name
      
